
spring:
  #dubbo
  dubbo:
    application:
      name: manage-web # dubbo 服务名称
    registry:
      protocol: zookeeper # zookeeper 通讯协议名称
      address: 192.168.0.104:2181  #注册中心地址
    base-package: com.tyrant.gmall # 扫描的包
    protocol:
      name: dubbo # dubbo 通讯协议名称
    consumer:
      timeout: 600000 # 连接超时
      check: false # 检查service是否启动

server:
  port: 8091

#日志等级
logging:
  level: debug

